### ISSUE TITLE
needed a couple of tweaks for Ubuntu 14.4

### ISSUE THREAD

**Issue by maruchi-usa** [mrlesmithjr/ansible-openldap#2]
Thank you, Larry for this playbook.
I had to a couple of tweak to get it to work with Ubuntu 14.4.
1) pip was upgraded - O/S provided pip failed to install ansible
2) use "service" for Ubuntu14.4 instead of "systemd"

By the way, I could not figure out what the following statement does:
when: >

**Comment by mrlesmithjr** [comment]
@maruchi-usa do you have the rest of the `when:` condition to share here by chance? Also, did you test this with the included Vagrant environment? Just for clarity that is.

**Comment by maruchi-usa** [comment]
Hi Larry,

Yes, I did test with included Vagrant.
2 Files are changed: **provision.sh** and **config_openldap.yml**
Sorry, I had not updated "when: clause" to target 14.4 as apposed to 16.4.

[https://github.com/maruchi-usa/ansible-openldap/commit/3205ed11684b02ad17a76ea5ea618a4dd9aea181](url)

**Comment by mrlesmithjr** [comment]
I guess we can close this out now ;)
As #3 should have resolved this
