### ISSUE TITLE
php-xml missing

### ISSUE THREAD

**Issue by LPottmeier** [mrlesmithjr/ansible-openldap#5]
Phpldap admin complained about a missin PHP XML Library on first start. 
Putting it in the packages vars solved th problem for me. Maybe at that in the defaults

`
vars:
- openldap_debian_packages:
       - slapd
       - ldap-utils
       - php-xml
       - phpldapadmin`

**Comment by mrlesmithjr** [comment]
@LPottmeier Want to submit a PR for this?

**Comment by LPottmeier** [comment]
Yes,  but I can't create a new branch, to place it.

**Comment by LPottmeier** [comment]
Ok, sorry RTFM :https://help.github.com/articles/creating-a-pull-request/ I will try

**Comment by mrlesmithjr** [comment]
LOL! Great job!
